version: '3'

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - box-prod-postgres-data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - box-prod-redis-data:/data

  django:
    build:
      context: ../..
      dockerfile: ./containers/docker/django/Dockerfile
    command: /usr/local/bin/gunicorn box.wsgi:application -w 2 -b :8000
    env_file: ../../.env
    environment:
      DJANGO_ENV: development
    volumes:
      - box-prod-django-data:/code
      - box-prod-django-static:/box/static/
      - box-prod-django-media:/box/media/
    depends_on:
      - postgres
      - redis

  certbot:
    image: certbot/certbot
    volumes:
      - ../docker/certbot/conf:/etc/letsencrypt
      - ../docker/certbot/www:/var/www/certbot

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../docker/nginx/config/nginx/conf.d:/etc/nginx/conf.d
      - ../docker/certbot/conf:/etc/letsencrypt
      - ../docker/certbot/www:/var/www/certbot
      - box-prod-django-static:/box/static/
      - box-prod-django-media:/box/media/
    depends_on:
      - django

volumes:
  box-prod-django-data:
  box-prod-django-static:
  box-prod-django-media:
  box-prod-redis-data:
  box-prod-postgres-data:
