version: '3'

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - {{ cookiecutter.project_slug }}-prod-postgres-data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - {{ cookiecutter.project_slug }}-prod-redis-data:/data

  django:
    build:
      context: ../..
      dockerfile: ./containers/docker/production/django/Dockerfile
    command: /usr/local/bin/gunicorn {{ cookiecutter.project_slug }}.wsgi:application -w 2 -b :8000
    env_file: ../../.env
    environment:
      DJANGO_ENV: production
    volumes:
      - {{ cookiecutter.project_slug }}-prod-django-data:/code
      - {{ cookiecutter.project_slug }}-prod-django-static:/{{ cookiecutter.project_slug }}/static/
      - {{ cookiecutter.project_slug }}-prod-django-media:/{{ cookiecutter.project_slug }}/media/
    depends_on:
      - postgres
      - redis

  certbot:
    image: certbot/certbot
    volumes:
      - ../docker/production/certbot/conf:/etc/letsencrypt
      - ../docker/production/certbot/www:/var/www/certbot

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../docker/production/nginx/conf.d:/etc/nginx/conf.d
      - ../docker/production/certbot/conf:/etc/letsencrypt
      - ../docker/production/certbot/www:/var/www/certbot
      - {{ cookiecutter.project_slug }}-prod-django-static:/{{ cookiecutter.project_slug }}/static/
      - {{ cookiecutter.project_slug }}-prod-django-media:/{{ cookiecutter.project_slug }}/media/
    depends_on:
      - django

volumes:
  {{ cookiecutter.project_slug }}-prod-django-data:
  {{ cookiecutter.project_slug }}-prod-django-static:
  {{ cookiecutter.project_slug }}-prod-django-media:
  {{ cookiecutter.project_slug }}-prod-redis-data:
  {{ cookiecutter.project_slug }}-prod-postgres-data:
